# GitHub workflow
name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
          ./scripts/InstallChrome.sh
      - name: Run Django unit tests
        run: |
          pip3 install --user django
          pip3 install --user selenium
          python3 manage.py test